### ISSUE TITLE
Why does `extractPublicKey` require a `PeerId`?

### ISSUE THREAD

**Issue by npfoss** [ipfs/js-ipns#25]
It looks like that PeerId's public key is returned if there isn't one in the record, but I'm not sure what the point of that is...

**Comment by vasco-santos** [comment]
Hey @npfoss 

We require a `PeerId` because according to the type of cryptographic keys being used, we may want to have it insider `PeerId` instead of insider the ipns record. Check https://github.com/ipfs/js-ipns/blob/master/src/pb/ipns.proto.js#L22-L25 for further details.

I will be closing the issue. Feel free to re-open it if you feel necessary

**Comment by npfoss** [comment]
I see, thanks for the explanation. Maybe it's just me because I'm using the old RSA keys, but this leads to a seeming anti-pattern of writing
```js
ipns.extractPublicKey({ pubKey: 'dummy' }, record, ...
```
I don't know as much about the other use cases though so I believe you that the benefit there probably outweighs this detriment. Just thought I'd follow up to clarify.
