### ISSUE TITLE
fails silently (given invalid pubkey)

### ISSUE THREAD

**Issue by npfoss** [ipfs/js-ipns#28]
```js
const PeerId = require('peer-id')
const pid = await PeerId.create({ bits: 256, keyType: 'ed25519' })
const ipns = require('ipns')
ipns.create(pid.privKey, 'test value', 5, 100, (err, rec) => {
  console.error(err);
  console.log(rec);
})
// doesn't print anything or throw an error, just returns undefined :(
```

Throwing an 'unsupported key type' error or something would be way more helpful.

**Comment by vasco-santos** [comment]
I believe that that is happening because we are still using an older version of `peer-id` compared to what you installed here.

This way, the following line:

https://github.com/ipfs/js-ipns/blob/master/src/index.js#L248

should be promisifying what does not have a callback anymore and something strange is happening. Can you try that with a `0.12.*` `peer-id`?

**Comment by npfoss** [comment]
You're right, that's what was happening, thanks! So the real problem here is that this version of promisify doesn't throw errors on invalid inputs?

**Comment by vasco-santos** [comment]
I think that it is because `promisify` really expects a function with callback in the last parameter to be provided, which is not the case here.

**Comment by npfoss** [comment]
You would think that should throw an error on their side...

Closing since this isn't a js-ipns problem.
