### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipns#33]
I see this intermittent problem very, very often in CI:

```
ipfs:   ipns-pubsub
ipfs: wait for republish as we can receive the republish message first
ipfs:     ✓ should get enabled state of pubsub
ipfs:     1) should publish the received record to a go node and a js subscriber should receive it
ipfs: Error: Timeout stopping go node. Process 7773 will be force killed now.
ipfs:     at Timeout.setTimeout [as _onTimeout] (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/node_modules/ipfsd-ctl/src/ipfsd-daemon.js:243:23)
ipfs:     at ontimeout (timers.js:436:11)
ipfs:     at tryOnTimeout (timers.js:300:5)
ipfs:     at listOnTimeout (timers.js:263:5)
ipfs:     at Timer.processTimers (timers.js:223:10)
ipfs:   1 passing (1m)
ipfs:   1 failing
ipfs:   1) ipns-pubsub
ipfs:        should publish the received record to a go node and a js subscriber should receive it:
ipfs:      HTTPError: failed to find any peer in table
ipfs:       at Object.errorHandler [as handleError] (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/lib/core.js:67:15)
ipfs:       at async Client.fetch (/Users/travis/build/ipfs/js-ipfs/node_modules/ipfs-utils/src/http.js:145:9)
ipfs:       at async Object.publish (/Users/travis/build/ipfs/js-ipfs/packages/ipfs-http-client/src/name/publish.js:9:17)
ipfs:       at async subscribeToReceiveByPubsub (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/test/ipns-pubsub.js:103:16)
ipfs:       at async Context.<anonymous> (/Users/travis/build/ipfs/js-ipfs/packages/ipfs/node_modules/ipfs-interop/test/ipns-pubsub.js:73:5)
```

Any ideas what could be causing it?  Are the tests not connecting the nodes together properly?

**Comment by vasco-santos** [comment]
Hey @achingbrain 

That error comes from `go-ipfs` on publish the record.

I cannot find the exact error on github now because it apparently does not exist anymore in the latest changes in the DHT, just found an old test for ir: https://github.com/libp2p/go-libp2p-kad-dht/blob/8a4963d4925ab7c396b8254740b10747145ff86a/dht_test.go#L1678

However, if you get the code of the installed version of `go-libp2p-kad-dht` and check it out, you will be able to find what it means. IIRC, it means that the node is not yet connected to any other node, and the DHT needs  another node to put. This happens because `go-ipfs` has the DHT enabled by default, so in this test go is also publishing the IPNS record to the dht.

So, this issue seems not related with `js-ipns`, but a lack of connectivity between the nodes.

**Comment by achingbrain** [comment]
You are quite right - if I add a second go-ipfs node to the test and get the two go-ipfs nodes to dial each other, it passes.  Ugh.

**Comment by achingbrain** [comment]
Aaah, a little further up it configures the nodes to connect to a bootstrap because, yes, they need another node in the swarm.  And the bootstrap node is.. down.

**Comment by vasco-santos** [comment]
Oh, the bootstrap node being down explains it!
